baseURL = "https://hugoamp.netlify.com/"
languageCode = "ja"
title = "JavaScriptに関するお知らせ"
theme = "hugo_theme_robust"

[outputs]
home = [ "HTML", "AMP" ]
page = [ "HTML", "AMP" ]


[params]
dateformat = "2006-01-02"

[params.author]
  thumbnail = "images/icon.svg"
  name = "Ryuto MIZUTANI"
  description = '名古屋発Webエンジニア'
  twitter  = "https://twitter.com/sirycity"
  github   = "https://github.com/SiryCity"
  mail     = "sirycity2018@gmail.com"